import type { Metadata } from "next";
import { pt_sans, open_sans, cooper_hewitt } from "@/lib/fonts";
import "@/styles/globals.css";
import AppProviders from "@/components/providers/AppProviders";
import Navbar from "@/components/layout/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-rostr-bg-dark">
      <head>
        <meta charSet="utf-8" name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${pt_sans.variable} ${open_sans.variable} ${cooper_hewitt.variable} font-body h-full`}>
        <AppProviders>
          <Navbar />
          {children}
          {/* <Footer /> */}
          </AppProviders>
      </body>
    </html>
  );
}
